In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_digits

In [3]:
dataset=load_digits()
dir(dataset)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [4]:
x_train,x_test,y_train,y_test=train_test_split(dataset.data,dataset.target,test_size=0.2)

In [5]:
le= LogisticRegression()

In [6]:
le.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [7]:
le.predict(x_test)

array([8, 1, 7, 6, 0, 8, 8, 4, 6, 7, 7, 7, 7, 6, 0, 2, 7, 2, 4, 4, 8, 6,
       8, 7, 9, 0, 2, 4, 2, 7, 2, 1, 8, 6, 6, 8, 0, 0, 6, 5, 4, 8, 3, 4,
       6, 9, 5, 1, 4, 7, 0, 3, 7, 2, 2, 6, 5, 8, 1, 1, 8, 2, 0, 2, 1, 2,
       1, 1, 2, 5, 7, 1, 9, 9, 1, 3, 2, 6, 7, 2, 5, 1, 3, 2, 1, 4, 0, 5,
       4, 1, 3, 2, 9, 7, 6, 2, 5, 0, 7, 3, 5, 2, 6, 2, 3, 6, 2, 7, 3, 0,
       9, 3, 3, 7, 8, 8, 8, 1, 0, 1, 8, 2, 2, 0, 9, 8, 6, 7, 6, 9, 1, 9,
       6, 1, 0, 0, 2, 6, 7, 9, 8, 7, 9, 6, 1, 6, 4, 6, 1, 8, 9, 0, 0, 0,
       6, 4, 3, 9, 1, 8, 7, 4, 8, 1, 9, 9, 0, 2, 6, 9, 7, 1, 4, 1, 5, 8,
       9, 9, 3, 2, 4, 1, 3, 3, 5, 5, 3, 2, 9, 8, 0, 8, 5, 2, 6, 5, 2, 0,
       7, 5, 0, 4, 8, 6, 3, 5, 0, 2, 4, 3, 8, 4, 9, 0, 4, 8, 4, 8, 7, 3,
       5, 8, 5, 4, 4, 2, 9, 5, 6, 7, 6, 2, 6, 3, 6, 2, 6, 2, 5, 0, 9, 6,
       5, 3, 2, 0, 1, 1, 8, 3, 0, 7, 0, 3, 0, 5, 9, 5, 3, 0, 4, 6, 3, 9,
       9, 4, 1, 4, 1, 2, 1, 7, 4, 5, 7, 4, 1, 2, 7, 0, 7, 9, 1, 8, 5, 7,
       4, 3, 5, 8, 6, 9, 4, 8, 0, 6, 0, 6, 6, 4, 6,

In [10]:
le.score(x_train,y_train)

1.0

In [12]:
rf=RandomForestClassifier()

In [13]:
rf.fit(x_train,y_train)

RandomForestClassifier()

In [14]:
rf.predict(x_test)

array([8, 1, 7, 6, 0, 8, 1, 4, 6, 7, 7, 7, 7, 6, 0, 2, 7, 2, 4, 4, 8, 6,
       8, 7, 8, 0, 2, 4, 2, 7, 2, 1, 9, 6, 6, 8, 4, 0, 6, 5, 4, 8, 3, 4,
       6, 9, 5, 1, 4, 7, 0, 3, 7, 2, 2, 6, 5, 8, 1, 1, 8, 2, 0, 2, 1, 2,
       1, 1, 2, 5, 7, 1, 9, 9, 8, 3, 2, 6, 7, 2, 5, 1, 3, 2, 1, 4, 0, 5,
       4, 1, 3, 2, 9, 7, 6, 2, 5, 0, 7, 3, 5, 2, 6, 5, 3, 6, 2, 7, 3, 0,
       9, 3, 3, 7, 8, 8, 8, 1, 0, 1, 8, 2, 2, 0, 9, 8, 6, 7, 6, 9, 1, 9,
       6, 1, 0, 0, 2, 6, 7, 9, 8, 7, 9, 6, 1, 6, 4, 6, 1, 9, 9, 0, 0, 0,
       6, 4, 3, 9, 1, 8, 7, 4, 8, 5, 9, 9, 0, 2, 6, 9, 7, 1, 4, 1, 5, 8,
       9, 9, 3, 2, 4, 1, 3, 3, 5, 5, 3, 2, 9, 8, 0, 8, 5, 2, 6, 5, 2, 0,
       7, 5, 0, 4, 8, 6, 3, 5, 0, 2, 4, 3, 8, 4, 9, 0, 4, 8, 4, 8, 7, 3,
       5, 8, 5, 1, 4, 2, 9, 5, 6, 7, 6, 2, 6, 9, 6, 2, 6, 2, 5, 0, 9, 6,
       5, 3, 2, 0, 1, 1, 8, 3, 0, 7, 0, 3, 0, 5, 9, 5, 3, 0, 4, 6, 3, 9,
       9, 4, 1, 4, 1, 2, 1, 7, 4, 5, 7, 4, 1, 2, 7, 0, 7, 9, 1, 8, 5, 7,
       4, 3, 5, 8, 6, 9, 4, 8, 0, 6, 0, 6, 6, 4, 6,

In [15]:
rf.score(x_train,y_train)

1.0

In [9]:
cross_val_score(LogisticRegression(),dataset.data,dataset.target)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [16]:
cross_val_score(RandomForestClassifier(),dataset.data,dataset.target)

array([0.93611111, 0.91666667, 0.95543175, 0.9637883 , 0.9275766 ])