In [30]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import joblib
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [3]:
df=pd.read_csv("carprices.csv")
df

Car_Model  Mileage  Sell_Price  Age
0                  BMW X5    69000       18000    6
1                  BMW X5    35000       34000    3
2                  BMW X5    57000       26100    5
3                  BMW X5    22500       40000    2
4                  BMW X5    46000       31500    4
5                 Audi A5    59000       29400    5
6                 Audi A5    52000       32000    5
7                 Audi A5    72000       19300    6
8                 Audi A5    91000       12000    8
9   Mercedez_Benz_C_class    67000       22000    6
10  Mercedez_Benz_C_class    83000       20000    7
11  Mercedez_Benz_C_class    79000       21000    7
12  Mercedez_Benz_C_class    59000       33000    5

In [4]:
le=LabelEncoder()
f=le.fit_transform(df[["Car_Model"]])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [5]:
f

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 2, 2, 2, 2])

In [7]:
df["Car_Model"]=f
df

Car_Model  Mileage  Sell_Price  Age
0           1    69000       18000    6
1           1    35000       34000    3
2           1    57000       26100    5
3           1    22500       40000    2
4           1    46000       31500    4
5           0    59000       29400    5
6           0    52000       32000    5
7           0    72000       19300    6
8           0    91000       12000    8
9           2    67000       22000    6
10          2    83000       20000    7
11          2    79000       21000    7
12          2    59000       33000    5

In [9]:
x=df[["Car_Model","Mileage","Age"]].values

In [10]:
x

array([[    1, 69000,     6],
       [    1, 35000,     3],
       [    1, 57000,     5],
       [    1, 22500,     2],
       [    1, 46000,     4],
       [    0, 59000,     5],
       [    0, 52000,     5],
       [    0, 72000,     6],
       [    0, 91000,     8],
       [    2, 67000,     6],
       [    2, 83000,     7],
       [    2, 79000,     7],
       [    2, 59000,     5]])

In [13]:
y=df[["Sell_Price"]].values
y

array([[18000],
       [34000],
       [26100],
       [40000],
       [31500],
       [29400],
       [32000],
       [19300],
       [12000],
       [22000],
       [20000],
       [21000],
       [33000]])

In [38]:
Column_Transformer=ColumnTransformer(
    transformers=[("encoder",OneHotEncoder(),[0])],
    remainder="passthrough"
    )
x_transfered=Column_Transformer.fit_transform(x)

In [40]:
x_transfered

array([[0.00e+00, 1.00e+00, 0.00e+00, 6.90e+04, 6.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 3.50e+04, 3.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 5.70e+04, 5.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 2.25e+04, 2.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 4.60e+04, 4.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 5.90e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 5.20e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 7.20e+04, 6.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 9.10e+04, 8.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 6.70e+04, 6.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 8.30e+04, 7.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 7.90e+04, 7.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 5.90e+04, 5.00e+00]])

In [59]:
x_=x_transfered[:,1:]


In [60]:
reg=linear_model.LinearRegression()


In [61]:
reg.fit(x_,y)

LinearRegression()

In [63]:
reg.predict([[1,0,6000,3]])

array([[46020.32519372]])